const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, '../frontend/dist');

function getMimeType(ext) {
  const mime = {
    '.html': 'text/html',
    '.js': 'application/javascript',
    '.css': 'text/css',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.json': 'application/json',
    '.woff2': 'font/woff2',
    '.woff': 'font/woff',
  };
  return mime[ext] || 'application/octet-stream';
}

function collectFiles(dir) {
  const result = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const sub = collectFiles(fullPath);
      Object.assign(result, sub);
    } else {
      const relativePath = fullPath.replace(distDir, '').replace(/\\/g, '/');
      const content = fs.readFileSync(fullPath, 'utf-8');
      const ext = path.extname(entry.name);
      result[relativePath] = { content, mime: getMimeType(ext) };
    }
  }
  return result;
}

const files = collectFiles(distDir);

let output = `// Auto-generated by build-embeds.js\n`;
output += `// DO NOT EDIT MANUALLY - Rebuild with: node build-embeds.js\n\n`;

output += `const files = ${JSON.stringify(files, null, 2)};\n\n`;
output += `function serveEmbedded(req, res, next) {\n`;
output += `  const urlPath = req.path === '/' ? '/index.html' : req.path;\n`;
output += `  if (files[urlPath]) {\n`;
output += `    res.type(files[urlPath].mime);\n`;
output += `    return res.send(files[urlPath].content);\n`;
output += `  }\n`;
output += `  // SPA fallback\n`;
output += `  res.type('text/html');\n`;
output += `  res.send(files['/index.html'].content);\n`;
output += `}\n\n`;
output += `module.exports = { serveEmbedded, files };\n`;

const outPath = path.join(__dirname, 'embeds.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`Generated embeds.js with ${Object.keys(files).length} files`);
